// CA Intermediate 6 Papers - Complete Default Seed Syllabus
// Exactly matching the official structure without any "Module" headings

export const PAPERS_METADATA = [
  {
    id: "paper1",
    code: "Paper 1",
    name: "Advanced Accounting",
    shortName: "Adv. Accounts",
    icon: "📊",
    color: "#ffb7b2",
    accent: "#ff6f69"
  },
  {
    id: "paper2",
    code: "Paper 2",
    name: "Corporate and Other Laws",
    shortName: "Corp. Laws",
    icon: "⚖️",
    color: "#b5ead7",
    accent: "#48bb78"
  },
  {
    id: "paper3",
    code: "Paper 3",
    name: "Taxation",
    shortName: "Taxation",
    icon: "📑",
    color: "#c7ceea",
    accent: "#6b8af7"
  },
  {
    id: "paper4",
    code: "Paper 4",
    name: "Cost and Management Accounting",
    shortName: "Costing",
    icon: "🧮",
    color: "#ffdac1",
    accent: "#f6ad55"
  },
  {
    id: "paper5",
    code: "Paper 5",
    name: "Auditing and Ethics",
    shortName: "Audit & Ethics",
    icon: "🔍",
    color: "#e2f0cb",
    accent: "#38a169"
  },
  {
    id: "paper6",
    code: "Paper 6",
    name: "Financial Management and Strategic Management",
    shortName: "FM & SM",
    icon: "📈",
    color: "#e8dff5",
    accent: "#9f7aea"
  }
];

export const INITIAL_SYLLABUS = {
  paper1: [
    { id: "p1_1", title: "Chapter 1: Introduction to Accounting Standards", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p1_2", title: "Chapter 2: Framework for Preparation and Presentation of Financial Statements", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p1_3", title: "Chapter 3: Applicability of Accounting Standards", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p1_4", title: "Chapter 4: Presentation & Disclosures Based Accounting Standards", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p1_5", title: "Unit 1: Accounting Standard 1 Disclosure of Accounting Policies", status: "Not Started", revisions: 0, notes: "", priority: "Low" },
    { id: "p1_6", title: "Unit 2: Accounting Standard 3 Cash Flow Statement", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p1_7", title: "Unit 3: Accounting Standard 17 Segment Reporting", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p1_8", title: "Unit 4: Accounting Standard 18 Related Party Disclosures", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p1_9", title: "Unit 5: Accounting Standard 20 Earnings Per Share", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p1_10", title: "Unit 6: Accounting Standard 24 Discontinuing Operations", status: "Not Started", revisions: 0, notes: "", priority: "Low" },
    { id: "p1_11", title: "Unit 7: Accounting Standard 25 Interim Financial Reporting", status: "Not Started", revisions: 0, notes: "", priority: "Low" },
    { id: "p1_12", title: "Chapter 5: Assets Based Accounting Standards", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p1_13", title: "Unit 1: Accounting Standard 2 Valuation of Inventory", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p1_14", title: "Unit 2: Accounting Standard 10 Property, Plant and Equipment", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p1_15", title: "Unit 3: Accounting Standard 13 Accounting for Investments", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p1_16", title: "Unit 4: Accounting Standard 16 Borrowing Costs", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p1_17", title: "Unit 5: Accounting Standard 19 Leases", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p1_18", title: "Unit 6: Accounting Standard 26 Intangible Assets", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p1_19", title: "Unit 7: Accounting Standard 28 Impairment of Assets", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p1_20", title: "Chapter 6: Liabilities Based Accounting Standards", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p1_21", title: "Unit 1: Accounting Standard 15 Employee Benefits", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p1_22", title: "Unit 2: AS 29 (Revised) Provisions, Contingent Liabilities and Contingent Assets", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p1_23", title: "Chapter 7: Accounting Standards Based on Items Impacting Financial Statement", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p1_24", title: "Unit 1: Accounting Standard 4 Contingencies and Events occurring after the Balance Sheet Date", status: "Not Started", revisions: 0, notes: "", priority: "Low" },
    { id: "p1_25", title: "Unit 2: Accounting Standard 5 Net Profit or Loss for the Period, Prior Period Items and Changes in Accounting Policies", status: "Not Started", revisions: 0, notes: "", priority: "Low" },
    { id: "p1_26", title: "Unit 3: Accounting Standard 11 The Effects of Changes in Foreign Exchange Rates", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p1_27", title: "Unit 4: Accounting Standard 22 Accounting for Taxes on Income", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p1_28", title: "Chapter 8: Revenue Based Accounting Standards", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p1_29", title: "Unit 1: Accounting Standard 7 Construction Contracts", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p1_30", title: "Unit 2: Accounting Standard 9 Revenue Recognition", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p1_31", title: "Chapter 9: Other Accounting Standards", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p1_32", title: "Unit 1: Accounting Standard 12 Accounting for Government Grants", status: "Not Started", revisions: 0, notes: "", priority: "Low" },
    { id: "p1_33", title: "Unit 2: Accounting Standard 14 Accounting for Amalgamations", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p1_34", title: "Chapter 10: Accounting Standards for Consolidated Financial Statement", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p1_35", title: "Unit 1: Accounting Standard 21 Consolidated Financial Statements", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p1_36", title: "Unit 2: Accounting Standard 23 Accounting for Investments in Associates in Consolidated Financial Statements", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p1_37", title: "Unit 3: Accounting Standard 27 Financial Reporting of Interests in Joint Ventures", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p1_38", title: "Chapter 11: Financial Statements of Companies", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p1_39", title: "Unit 1: Preparation of Financial Statements", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p1_40", title: "Unit 2: Cash Flow Statement", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p1_41", title: "Annexure", status: "Not Started", revisions: 0, notes: "", priority: "Low" },
    { id: "p1_42", title: "Chapter 12: Buyback of Securities", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p1_43", title: "Chapter 13: Amalgamation of Companies", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p1_44", title: "Chapter 14: Internal Reconstruction", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p1_45", title: "Chapter 15: Accounting for Branches including Foreign Branches", status: "Not Started", revisions: 0, notes: "", priority: "High" }
  ],
  paper2: [
    { id: "p2_1", title: "Chapter 1: Preliminary", status: "Not Started", revisions: 0, notes: "", priority: "Low" },
    { id: "p2_2", title: "Chapter 2: Incorporation of Company and Matters Incidental Thereto", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p2_3", title: "Chapter 3: Prospectus and Allotment of Securities", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p2_4", title: "Chapter 4: Share Capital and Debentures", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p2_5", title: "Chapter 5: Acceptance of Deposits by Companies", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p2_6", title: "Chapter 6: Registration of Charges", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p2_7", title: "Chapter 7: Management & Administration", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p2_8", title: "Chapter 8: Declaration and Payment of Dividend", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p2_9", title: "Chapter 9: Accounts of Companies", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p2_10", title: "Chapter 10: Audit and Auditors", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p2_11", title: "Chapter 11: Companies Incorporated Outside India", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p2_12", title: "Chapter 12: The Limited Liability Partnership Act, 2008", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p2_13", title: "Chapter 1: The General Clauses Act, 1897", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p2_14", title: "Chapter 2: Interpretation of Statutes", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p2_15", title: "Chapter 3: The Foreign Exchange Management Act, 1999", status: "Not Started", revisions: 0, notes: "", priority: "High" }
  ],
  paper3: [
    { id: "p3_1", title: "Chapter 1: Basic Concepts", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p3_2", title: "Chapter 2: Residence and Scope of Total Income", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p3_3", title: "Chapter 3: Heads of Income", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p3_4", title: "Unit 1: Salaries", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p3_5", title: "Unit 2: Income from House Property", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p3_6", title: "Unit 3: Profits and Gains of Business or Profession", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p3_7", title: "Unit 4: Capital Gains", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p3_8", title: "Unit 5: Income from Other Sources", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p3_9", title: "Chapter 4: Income of Other Persons included in Assessee's Total Income", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p3_10", title: "Chapter 5: Aggregation of Income, Set-Off and Carry Forward of Losses", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p3_11", title: "Chapter 6: Deductions from Gross Total Income", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p3_12", title: "Chapter 7: Advance Tax, Tax Deduction at Source and Tax Collection at Source", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p3_13", title: "Chapter 8: Provisions for filing Return of Income and Self Assessment", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p3_14", title: "Chapter 9: Income Tax Liability - Computation and Optimisation", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p3_15", title: "Chapter 1: GST in India - An Introduction", status: "Not Started", revisions: 0, notes: "", priority: "Low" },
    { id: "p3_16", title: "Chapter 2: Supply under GST", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p3_17", title: "Chapter 3: Charge of GST", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p3_18", title: "Chapter 4: Place of Supply", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p3_19", title: "Chapter 5: Exemptions from GST", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p3_20", title: "Chapter 6: Time of Supply", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p3_21", title: "Chapter 7: Value of Supply", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p3_22", title: "Chapter 8: Input Tax Credit", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p3_23", title: "Chapter 9: Registration", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p3_24", title: "Chapter 10: Tax Invoice; Credit and Debit Notes", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p3_25", title: "Chapter 11: Accounts and Records", status: "Not Started", revisions: 0, notes: "", priority: "Low" },
    { id: "p3_26", title: "Chapter 12: E-Way Bill", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p3_27", title: "Chapter 13: Payment of Tax", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p3_28", title: "Chapter 14: Tax Deduction at Source and Collection of Tax at Source", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p3_29", title: "Chapter 15: Returns", status: "Not Started", revisions: 0, notes: "", priority: "Medium" }
  ],
  paper4: [
    { id: "p4_1", title: "Chapter 1: Introduction to Cost and Management Accounting", status: "Not Started", revisions: 0, notes: "", priority: "Low" },
    { id: "p4_2", title: "Chapter 2: Material Cost", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p4_3", title: "Chapter 3: Employee Cost and Direct Expenses", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p4_4", title: "Chapter 4: Overheads – Absorption Costing Method", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p4_5", title: "Chapter 5: Activity Based Costing", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p4_6", title: "Chapter 6: Cost Sheet", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p4_7", title: "Chapter 7: Cost Accounting Systems", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p4_8", title: "Chapter 8: Unit & Batch Costing", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p4_9", title: "Chapter 9: Job Costing", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p4_10", title: "Chapter 10: Process & Operation Costing", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p4_11", title: "Chapter 11: Joint Products and By Products", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p4_12", title: "Chapter 12: Service Costing", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p4_13", title: "Chapter 13: Standard Costing", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p4_14", title: "Chapter 14: Marginal Costing", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p4_15", title: "Chapter 15: Budgets and Budgetary Control", status: "Not Started", revisions: 0, notes: "", priority: "High" }
  ],
  paper5: [
    { id: "p5_1", title: "Chapter 1: Nature, Objective and Scope of Audit", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p5_2", title: "Chapter 2: Audit Strategy, Audit Planning and Audit Programme", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p5_3", title: "Chapter 3: Risk Assessment and Internal Control", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p5_4", title: "Chapter 4: Audit Evidence", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p5_5", title: "Chapter 5: Audit of Items of Financial Statements", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p5_6", title: "Chapter 6: Audit Documentation", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p5_7", title: "Chapter 7: Completion and Review", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p5_8", title: "Chapter 8: Audit Report", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p5_9", title: "Chapter 9: Special Features of Audit of Different Type of Entities", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p5_10", title: "Chapter 10: Audit of Banks", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p5_11", title: "Chapter 11: Ethics and Terms of Audit Engagements", status: "Not Started", revisions: 0, notes: "", priority: "High" }
  ],
  paper6: [
    { id: "p6_1", title: "Chapter 1: Scope and Objectives of Financial Management", status: "Not Started", revisions: 0, notes: "", priority: "Low" },
    { id: "p6_2", title: "Chapter 2: Types of Financing", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p6_3", title: "Chapter 3: Financial Analysis and Planning – Ratio Analysis", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p6_4", title: "Chapter 4: Cost of Capital", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p6_5", title: "Chapter 5: Financing Decisions – Capital Structure", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p6_6", title: "Chapter 6: Financing Decisions – Leverages", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p6_7", title: "Chapter 7: Investment Decisions", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p6_8", title: "Chapter 8: Dividend Decision", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p6_9", title: "Chapter 9: Management of Working Capital", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p6_10", title: "Unit I: Introduction to Working Capital Management", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p6_11", title: "Unit II: Treasury and Cash Management", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p6_12", title: "Unit III: Management of Inventory", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p6_13", title: "Unit IV: Management of Receivables", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p6_14", title: "Unit V: Management of Payables (Creditors)", status: "Not Started", revisions: 0, notes: "", priority: "Low" },
    { id: "p6_15", title: "Unit VI: Financing of Working Capital", status: "Not Started", revisions: 0, notes: "", priority: "Medium" },
    { id: "p6_16", title: "Chapter 1: Introduction to Strategic Management", status: "Not Started", revisions: 0, notes: "", priority: "Low" },
    { id: "p6_17", title: "Chapter 2: Strategic Analysis: External Environment", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p6_18", title: "Chapter 3: Strategic Analysis: Internal Environment", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p6_19", title: "Chapter 4: Strategic Choices", status: "Not Started", revisions: 0, notes: "", priority: "High" },
    { id: "p6_20", title: "Chapter 5: Strategy Implementation and Evaluation", status: "Not Started", revisions: 0, notes: "", priority: "High" }
  ]
};
